[mcp_servers.godot]
command = "cmd"
args = [
    "/c",
    "npx",
    "-y",
    "@coding-solo/godot-mcp",
]

[mcp_servers.godot.env]
GODOT_PATH = 'C:\Users\saksham\AppData\Local\Microsoft\WinGet\Packages\GodotEngine.GodotEngine_Microsoft.Winget.Source_8wekyb3d8bbwe\Godot_v4.7.1-stable_win64_console.exe'
