extends GutTest

# test_ui_icons.gd
# M15.5 Requirement 1.4 — UIIcons is the single lookup point for every UI icon
# texture; every registered key must resolve to a real, loadable Texture2D
# rather than failing silently at runtime inside some UI scene.
#
# M22 Phase 2.5 addendum (2026-09-25) — two new keys, "research" and
# "cannonball", the only icons genuinely missing against the v0.3 design's
# resource-icon list (gold, rum, wood, iron, research, cannonball);
# generated by tools/ui_kit/gen_kit.py, not sourced/moved from anywhere
# (design.md §5a — "claude design outputs/" turned out to hold no new art
# at all, just duplicates of what's already in assets/).

const _EXPECTED_KEYS := [
	"gold", "wood", "iron", "rum", "health", "notoriety", "cannon_ready",
	"research", "cannonball",
]

func test_every_registered_icon_key_loads_a_real_texture():
	for key in _EXPECTED_KEYS:
		var tex := UIIcons.get_icon(key)
		assert_not_null(tex, "UIIcons.get_icon('%s') should return a texture" % key)
		if tex:
			assert_true(tex is Texture2D, "UIIcons.get_icon('%s') should be a Texture2D" % key)

func test_unregistered_key_returns_null_not_an_error():
	assert_null(UIIcons.get_icon("not_a_real_key"))

func test_the_two_new_m22_icons_have_a_sane_nonzero_size():
	for key in ["research", "cannonball"]:
		var tex := UIIcons.get_icon(key)
		var size := tex.get_size()
		assert_true(size.x > 0 and size.y > 0, "'%s' icon must have a non-zero size (got %s)" % [key, size])
