class_name UIIcons

## Purpose: single lookup point for every UI icon texture this project uses,
## mirroring PirateThemeBuilder's role as the one place theme values live —
## no scene or script should hardcode an assets/ui_icons/ path directly.
## Source: Kenney "Board Game Icons" (CC0, assets/ui_icons/LICENSE_board-game-icons.txt),
## white/monochrome glyphs meant to be tinted per-resource in code (see
## WorldHUD.gd's existing per-resource font colors, reused as icon modulate).
## Two of the seven keys are thematic substitutes, not literal matches — no
## CC0 pack found had a pirate coin or a rum bottle specifically:
##   "gold" uses the pack's generic circular token/chip icon.
##   "rum" uses the pack's potion-flask icon.
## Both read clearly at the sizes this HUD uses and keep the same "circular
## currency" / "bottled drink" silhouette a player would expect.

const _PATHS := {
	# M22 Phase 5.1 — painted full-colour resource icons (tools/ui_kit/
	# gen_kit.py, v0.3 icon spec) replace the Kenney white glyphs that were
	# tinted per resource in code; nothing should tint these any more.
	"gold":         "res://assets/ui/icons/gold.svg",
	"wood":         "res://assets/ui/icons/wood.svg",
	"iron":         "res://assets/ui/icons/iron.svg",
	"rum":          "res://assets/ui/icons/rum.svg",
	"health":       "res://assets/ui_icons/icons/health.png",
	"notoriety":    "res://assets/ui_icons/icons/notoriety.png",
	"cannon_ready": "res://assets/ui_icons/icons/cannon_ready.png",
	# M22 Phase 2.5 — the only two icons genuinely missing against the v0.3
	# design's resource-icon list (gold, rum, wood, iron, research,
	# cannonball); generated by tools/ui_kit/gen_kit.py, not sourced/moved
	# from anywhere (design.md §5a — "claude design outputs/" turned out to
	# hold no new art at all, just duplicates of what's already in assets/).
	"research":   "res://assets/ui/icons/research.svg",
	"cannonball": "res://assets/ui/icons/cannonball.svg",
	# M22 Phase 4.1 — MainMenu's round Settings button glyph. Not a resource
	# icon, but UIIcons is "every UI icon this project uses" per this file's
	# own header, not resources-only.
	"gear": "res://assets/ui/icons/gear.svg",
	# M22 Phase 5.5 — glyphs for the HUD's round utility-button rail.
	"log":      "res://assets/ui/icons/log.svg",
	"map":      "res://assets/ui/icons/map.svg",
	"codex":    "res://assets/ui/icons/codex.svg",
	"new":      "res://assets/ui/icons/new.svg",
	"wardrobe": "res://assets/ui/icons/wardrobe.svg",
	# M22 Phase 6c — the v0.3 notoriety-bar marker (bone disc + skull).
	"skull": "res://assets/ui/icons/skull.svg",
}

static func get_icon(key: String) -> Texture2D:
	if not _PATHS.has(key):
		push_warning("UIIcons: no icon registered for key '%s'" % key)
		return null
	var res = ResourceLoader.load(_PATHS[key])
	if res is Texture2D:
		return res as Texture2D
	push_warning("UIIcons: could not load icon texture: " + _PATHS[key])
	return null
